# Generated by Django 2.2.6 on 2019-11-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pizzaorder',
            constraint=models.UniqueConstraint(fields=('order', 'pizza', 'size'), name='Unique order pizza size'),
        ),
    ]
