# Generated by Django 2.2.6 on 2019-11-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191102_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='flavour',
            new_name='flavor',
        ),
    ]
