# Generated by Django 2.2.6 on 2019-11-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191102_0823'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PizzaOrder',
            new_name='OrderPizza',
        ),
    ]
