# Generated by Django 2.2.6 on 2019-11-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191102_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'travelling'), (3, 'delivered'), (4, 'cancelled')], default=1),
        ),
    ]
