# Generated by Django 2.2.6 on 2019-11-03 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191102_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpizza',
            options={'default_related_name': 'order_pizza'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Submitted'), (2, 'In Production'), (3, 'Travelling'), (4, 'Delivered'), (0, 'Cancelled')], default=1),
        ),
        migrations.AlterField(
            model_name='orderpizza',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_pizza', to='main.Order'),
        ),
        migrations.AlterField(
            model_name='orderpizza',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_pizza', to='main.Pizza'),
        ),
    ]
